version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/SaberManager
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: TimeManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_for_volume:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  postgres_data: